### ISSUE TITLE
tytompg

### ISSUE THREAD

**Issue by larsenv** [FozzTexx/viddin#1]
Hi,

Do you have a copy of tytompg you can give me?

Thanks.

**Comment by FozzTexx** [comment]
If you can't get it from the tytompg project then I don't know where you can get it. convert-ty is obsolete and I am no longer using it. 

I use tivo_dump to get videos off my TiVo these days:

https://web.archive.org/web/20110211224750/http://www.edsalisbury.net/linux/how-to-copy-videos-from-a-series-3-tivo-to-ubuntu-linux/
